# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import memory_pb2 as memory__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in memory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryStorageStub(object):
    """Memory Storage Service - Python backend
    Handles persistent storage, embeddings, and complex queries
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreEvent = channel.unary_unary(
                '/gladys.memory.MemoryStorage/StoreEvent',
                request_serializer=memory__pb2.StoreEventRequest.SerializeToString,
                response_deserializer=memory__pb2.StoreEventResponse.FromString,
                _registered_method=True)
        self.QueryByTime = channel.unary_unary(
                '/gladys.memory.MemoryStorage/QueryByTime',
                request_serializer=memory__pb2.QueryByTimeRequest.SerializeToString,
                response_deserializer=memory__pb2.QueryEventsResponse.FromString,
                _registered_method=True)
        self.QueryBySimilarity = channel.unary_unary(
                '/gladys.memory.MemoryStorage/QueryBySimilarity',
                request_serializer=memory__pb2.QueryBySimilarityRequest.SerializeToString,
                response_deserializer=memory__pb2.QueryEventsResponse.FromString,
                _registered_method=True)
        self.GenerateEmbedding = channel.unary_unary(
                '/gladys.memory.MemoryStorage/GenerateEmbedding',
                request_serializer=memory__pb2.GenerateEmbeddingRequest.SerializeToString,
                response_deserializer=memory__pb2.GenerateEmbeddingResponse.FromString,
                _registered_method=True)
        self.StoreHeuristic = channel.unary_unary(
                '/gladys.memory.MemoryStorage/StoreHeuristic',
                request_serializer=memory__pb2.StoreHeuristicRequest.SerializeToString,
                response_deserializer=memory__pb2.StoreHeuristicResponse.FromString,
                _registered_method=True)
        self.QueryHeuristics = channel.unary_unary(
                '/gladys.memory.MemoryStorage/QueryHeuristics',
                request_serializer=memory__pb2.QueryHeuristicsRequest.SerializeToString,
                response_deserializer=memory__pb2.QueryHeuristicsResponse.FromString,
                _registered_method=True)
        self.QueryMatchingHeuristics = channel.unary_unary(
                '/gladys.memory.MemoryStorage/QueryMatchingHeuristics',
                request_serializer=memory__pb2.QueryMatchingHeuristicsRequest.SerializeToString,
                response_deserializer=memory__pb2.QueryHeuristicsResponse.FromString,
                _registered_method=True)
        self.StoreEntity = channel.unary_unary(
                '/gladys.memory.MemoryStorage/StoreEntity',
                request_serializer=memory__pb2.StoreEntityRequest.SerializeToString,
                response_deserializer=memory__pb2.StoreEntityResponse.FromString,
                _registered_method=True)
        self.QueryEntities = channel.unary_unary(
                '/gladys.memory.MemoryStorage/QueryEntities',
                request_serializer=memory__pb2.QueryEntitiesRequest.SerializeToString,
                response_deserializer=memory__pb2.QueryEntitiesResponse.FromString,
                _registered_method=True)
        self.StoreRelationship = channel.unary_unary(
                '/gladys.memory.MemoryStorage/StoreRelationship',
                request_serializer=memory__pb2.StoreRelationshipRequest.SerializeToString,
                response_deserializer=memory__pb2.StoreRelationshipResponse.FromString,
                _registered_method=True)
        self.GetRelationships = channel.unary_unary(
                '/gladys.memory.MemoryStorage/GetRelationships',
                request_serializer=memory__pb2.GetRelationshipsRequest.SerializeToString,
                response_deserializer=memory__pb2.GetRelationshipsResponse.FromString,
                _registered_method=True)
        self.ExpandContext = channel.unary_unary(
                '/gladys.memory.MemoryStorage/ExpandContext',
                request_serializer=memory__pb2.ExpandContextRequest.SerializeToString,
                response_deserializer=memory__pb2.ExpandContextResponse.FromString,
                _registered_method=True)


class MemoryStorageServicer(object):
    """Memory Storage Service - Python backend
    Handles persistent storage, embeddings, and complex queries
    """

    def StoreEvent(self, request, context):
        """Store a new episodic event
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryByTime(self, request, context):
        """Query events by time range
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryBySimilarity(self, request, context):
        """Query events by embedding similarity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateEmbedding(self, request, context):
        """Generate embedding for text
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreHeuristic(self, request, context):
        """Store/update a heuristic
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryHeuristics(self, request, context):
        """Query heuristics by condition match (embedding similarity)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryMatchingHeuristics(self, request, context):
        """Query heuristics by text search (PostgreSQL tsvector)
        Used by Rust fast path on cache miss - faster than embedding similarity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreEntity(self, request, context):
        """--- Semantic Memory (Entities & Relationships) ---

        Store or update an entity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryEntities(self, request, context):
        """Query entities by name, type, or embedding
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreRelationship(self, request, context):
        """Store a relationship between entities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRelationships(self, request, context):
        """Get relationships for an entity (1-hop context)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExpandContext(self, request, context):
        """Expand context: get entity + relationships + related entities (for LLM prompts)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryStorageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreEvent,
                    request_deserializer=memory__pb2.StoreEventRequest.FromString,
                    response_serializer=memory__pb2.StoreEventResponse.SerializeToString,
            ),
            'QueryByTime': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryByTime,
                    request_deserializer=memory__pb2.QueryByTimeRequest.FromString,
                    response_serializer=memory__pb2.QueryEventsResponse.SerializeToString,
            ),
            'QueryBySimilarity': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryBySimilarity,
                    request_deserializer=memory__pb2.QueryBySimilarityRequest.FromString,
                    response_serializer=memory__pb2.QueryEventsResponse.SerializeToString,
            ),
            'GenerateEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateEmbedding,
                    request_deserializer=memory__pb2.GenerateEmbeddingRequest.FromString,
                    response_serializer=memory__pb2.GenerateEmbeddingResponse.SerializeToString,
            ),
            'StoreHeuristic': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreHeuristic,
                    request_deserializer=memory__pb2.StoreHeuristicRequest.FromString,
                    response_serializer=memory__pb2.StoreHeuristicResponse.SerializeToString,
            ),
            'QueryHeuristics': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryHeuristics,
                    request_deserializer=memory__pb2.QueryHeuristicsRequest.FromString,
                    response_serializer=memory__pb2.QueryHeuristicsResponse.SerializeToString,
            ),
            'QueryMatchingHeuristics': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryMatchingHeuristics,
                    request_deserializer=memory__pb2.QueryMatchingHeuristicsRequest.FromString,
                    response_serializer=memory__pb2.QueryHeuristicsResponse.SerializeToString,
            ),
            'StoreEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreEntity,
                    request_deserializer=memory__pb2.StoreEntityRequest.FromString,
                    response_serializer=memory__pb2.StoreEntityResponse.SerializeToString,
            ),
            'QueryEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryEntities,
                    request_deserializer=memory__pb2.QueryEntitiesRequest.FromString,
                    response_serializer=memory__pb2.QueryEntitiesResponse.SerializeToString,
            ),
            'StoreRelationship': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreRelationship,
                    request_deserializer=memory__pb2.StoreRelationshipRequest.FromString,
                    response_serializer=memory__pb2.StoreRelationshipResponse.SerializeToString,
            ),
            'GetRelationships': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRelationships,
                    request_deserializer=memory__pb2.GetRelationshipsRequest.FromString,
                    response_serializer=memory__pb2.GetRelationshipsResponse.SerializeToString,
            ),
            'ExpandContext': grpc.unary_unary_rpc_method_handler(
                    servicer.ExpandContext,
                    request_deserializer=memory__pb2.ExpandContextRequest.FromString,
                    response_serializer=memory__pb2.ExpandContextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gladys.memory.MemoryStorage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gladys.memory.MemoryStorage', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryStorage(object):
    """Memory Storage Service - Python backend
    Handles persistent storage, embeddings, and complex queries
    """

    @staticmethod
    def StoreEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gladys.memory.MemoryStorage/StoreEvent',
            memory__pb2.StoreEventRequest.SerializeToString,
            memory__pb2.StoreEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryByTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gladys.memory.MemoryStorage/QueryByTime',
            memory__pb2.QueryByTimeRequest.SerializeToString,
            memory__pb2.QueryEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryBySimilarity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gladys.memory.MemoryStorage/QueryBySimilarity',
            memory__pb2.QueryBySimilarityRequest.SerializeToString,
            memory__pb2.QueryEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gladys.memory.MemoryStorage/GenerateEmbedding',
            memory__pb2.GenerateEmbeddingRequest.SerializeToString,
            memory__pb2.GenerateEmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreHeuristic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gladys.memory.MemoryStorage/StoreHeuristic',
            memory__pb2.StoreHeuristicRequest.SerializeToString,
            memory__pb2.StoreHeuristicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryHeuristics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gladys.memory.MemoryStorage/QueryHeuristics',
            memory__pb2.QueryHeuristicsRequest.SerializeToString,
            memory__pb2.QueryHeuristicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryMatchingHeuristics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gladys.memory.MemoryStorage/QueryMatchingHeuristics',
            memory__pb2.QueryMatchingHeuristicsRequest.SerializeToString,
            memory__pb2.QueryHeuristicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gladys.memory.MemoryStorage/StoreEntity',
            memory__pb2.StoreEntityRequest.SerializeToString,
            memory__pb2.StoreEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gladys.memory.MemoryStorage/QueryEntities',
            memory__pb2.QueryEntitiesRequest.SerializeToString,
            memory__pb2.QueryEntitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreRelationship(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gladys.memory.MemoryStorage/StoreRelationship',
            memory__pb2.StoreRelationshipRequest.SerializeToString,
            memory__pb2.StoreRelationshipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRelationships(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gladys.memory.MemoryStorage/GetRelationships',
            memory__pb2.GetRelationshipsRequest.SerializeToString,
            memory__pb2.GetRelationshipsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExpandContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gladys.memory.MemoryStorage/ExpandContext',
            memory__pb2.ExpandContextRequest.SerializeToString,
            memory__pb2.ExpandContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SalienceGatewayStub(object):
    """Salience Gateway Service - the "amygdala"
    Co-located with Memory per ADR-0001 §5.1
    Provides fast salience evaluation for incoming events
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvaluateSalience = channel.unary_unary(
                '/gladys.memory.SalienceGateway/EvaluateSalience',
                request_serializer=memory__pb2.EvaluateSalienceRequest.SerializeToString,
                response_deserializer=memory__pb2.EvaluateSalienceResponse.FromString,
                _registered_method=True)


class SalienceGatewayServicer(object):
    """Salience Gateway Service - the "amygdala"
    Co-located with Memory per ADR-0001 §5.1
    Provides fast salience evaluation for incoming events
    """

    def EvaluateSalience(self, request, context):
        """Evaluate salience of an event
        Uses heuristics from Memory + novelty detection from Rust fast path
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SalienceGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvaluateSalience': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateSalience,
                    request_deserializer=memory__pb2.EvaluateSalienceRequest.FromString,
                    response_serializer=memory__pb2.EvaluateSalienceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gladys.memory.SalienceGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gladys.memory.SalienceGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SalienceGateway(object):
    """Salience Gateway Service - the "amygdala"
    Co-located with Memory per ADR-0001 §5.1
    Provides fast salience evaluation for incoming events
    """

    @staticmethod
    def EvaluateSalience(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gladys.memory.SalienceGateway/EvaluateSalience',
            memory__pb2.EvaluateSalienceRequest.SerializeToString,
            memory__pb2.EvaluateSalienceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
